In [1]:
import sys
import os
import platform
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import flopy.utils.binaryfile as bf
import flopy

flopy is installed in C:\Users\LENOVO\miniconda3\lib\site-packages\flopy

In [2]:
# Directorio de trabajo:
model_ws= "../../Outputs/Resultados_Base/"
modelname= 'RUCM_Base'
exe_name= '../../Solver/mf2005.exe'
ml= flopy.modflow.Modflow.load(modelname+'.nam', exe_name=exe_name, 
                               model_ws=model_ws, check=False)

In [3]:
# Archivo HDS
hds = bf.HeadFile(model_ws + '/' + modelname + '.hds')

In [4]:
totim = ml.dis.get_totim() #matriz de periodos
nper = ml.dis.nper #numero de periodos

In [5]:
# Funcion para extraer los heads en cada HOB en todos los Stress Periods
def f(Lay, Row, Col):
    head_ob = []
    period_ob = []
    
    for i in range(nper): #stress periods
        head=hds.get_data(kstpkper=(0,i))
        head_ob.append(head[Lay][Row][Col])  
    return head_ob

In [6]:
h_0818003 = f(0,55,103)
h_0818005 = f(1,10,48)
h_0818086 = f(2,64,103)
h_0824005 = f(0,39,60)
h_0824007 = f(0,43,21)
h_0824008 = f(0,67,35)
h_0824010 = f(0,45,71)
h_0824031 = f(0,36,41)
h_0824032 = f(0,65,63)
h_0824033 = f(0,25,45)
Periodo = [i+1 for i in range(nper)]

In [7]:
# Perlen
perlen = []
for i in range(nper):
    perlen.append(ml.dis.perlen[i])

In [8]:
lista = list(zip(Periodo,perlen,totim,h_0818003,h_0818005,h_0818086,h_0824005,
                 h_0824007,h_0824008,h_0824010,h_0824031, h_0824032,h_0824033))

In [9]:
ship_columns = ['Stress Period','Time','Total Time','08_18_003', '08_18_005', '08_18_086',
               '08_24_005', '08_24_007', '08_24_008', '08_24_010', '08_24_031',
               '08_24_032', '08_24_033']

In [10]:
Sim = pd.DataFrame(columns=ship_columns, data=lista)
Sim

,Stress Period,Time,Total Time,08_18_003,08_18_005,08_18_086,08_24_005,08_24_007,08_24_008,08_24_010,08_24_031,08_24_032,08_24_033
0,1,31.0,31.0,722.967285,728.000305,655.252625,709.004395,794.972046,607.016479,729.978699,787.978638,545.054749,743.312622
1,2,30.0,61.0,722.986633,728.033813,657.137878,709.022888,794.981506,607.063049,729.969421,787.984619,545.116272,743.619873
2,3,31.0,92.0,722.951111,728.033875,657.385925,709.027161,794.954041,607.077576,729.948486,787.955505,545.167419,743.915649
3,4,31.0,123.0,722.915222,728.033997,657.705322,709.031372,794.927490,607.091614,729.927795,787.923645,545.217041,744.206299
4,5,28.0,151.0,722.881287,728.034302,657.941895,709.035217,794.904175,607.104004,729.909424,787.893188,545.260681,744.459717
...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,428,31.0,13027.0,721.772095,730.744568,660.237305,710.700928,791.987122,609.440247,727.882690,776.709351,554.186646,746.860474
428,429,30.0,13057.0,721.741089,730.735779,659.890808,710.678040,791.973022,609.436646,727.870300,776.687866,554.195251,746.840881
429,430,31.0,13088.0,721.709167,730.726685,659.722168,710.634705,791.958801,609.433167,727.859558,776.665710,554.204346,746.821411
430,431,31.0,13119.0,721.680969,730.717896,659.668030,710.594238,791.944946,609.429932,727.848267,776.643616,554.213684,746.811218
431,432,30.0,13149.0,721.657166,730.709351,659.675354,710.580444,791.932251,609.427307,727.835510,776.624207,554.222839,746.810364

In [11]:
Sim.to_csv(os.path.join(model_ws, 'Valores_Simulados.csv'))